### ISSUE TITLE
VDJ data loading

### ISSUE THREAD

**Issue by jsmoon4** [rezakj/iCellR#11]
Hi, Thanks for this helpful tool.
I have a question to load VDJ data from 10X sequencing. I wanted to use prep.vdj function to load data, but the code has an error like this..
`my.vdj.1 <- prep.vdj(vdj.data = "G3_all_contig_annotations.csv", cond.name = "Pre")`
> Error in subset.default(my.vdj, productive == "True") : 
> object 'productive' not found 

In my data, 'productive' object exists with True and False. I don't know why this is not working.
Please let me know what is needed to be correct.
Many thanks.

**Comment by rezakj** [comment]
Would you run the example file to check. I just added an example file to the tutorial. I will soon add a full example with tutorials and more explanations. If you still get an error give me some time and I will fix it. I have been a bit busy but soon will debug more VDJ parts of the tool.

**Comment by jsmoon4** [comment]
Sorry for late reply.
In tutorial, I just found the example file with gene expression data.
Where is VDJ data in tutorial?

**Comment by rezakj** [comment]
First update iCellR to version 1.5.8. It's not in CRAN yet so update from GitHub.

Then add your VDJ data to iCellR object
my.obj <- add.vdj(my.obj, vdj.data = my.vdj.data)

The rest is explained in detail in the updated section for plotting "How to plot clonotypes".
