### ISSUE TITLE
load10x failed

### ISSUE THREAD

**Issue by jajcobyang** [rezakj/iCellR#13]
Hello,

I am trying to test out iCellR, however, I can't load my 10x data. 
rm(list = ls())
options(stringsAsFactors = F)

library(iCellR)

my.data <- load10x(dir.10x ='../reads' )

# Error: cannot allocate vector of size 6288.3 Gb

`
In reads, there 3 files : 
![image](https://user-images.githubusercontent.com/38162529/76124992-dda71000-5fc9-11ea-830a-a38b84d0449e.png)

Thanks!

**Comment by rezakj** [comment]
How many barcodes there are and how big those files are? It seems like it's memory issue.
