### ISSUE TITLE
how to produce a coverage corrected matrix

### ISSUE THREAD

**Issue by JLiLab** [rezakj/iCellR#14]
Thank you for sharing the pipeline!

I wonder if we can create a coverage corrected matrix and export it for other methods. The batch.aligned.data slot is empty after running combined coverage correction alignment. 

Thank you, 

James

**Comment by rezakj** [comment]
Hi James, 

Yes possible, 

run this:

```
my.obj <- run.pca(my.obj, method = "gene.model", gene.list = my.obj@gene.model,data.type = "main")

my.obj <- run.impute(my.obj, dims = 1:10, nn = 10, data.type = "pca")
```
And your data will be at `my.obj@imputed.data`

Reza

**Comment by JLiLab** [comment]
Thank you!
