### ISSUE TITLE
pseudotime.tree

### ISSUE THREAD

**Issue by Yale73** [rezakj/iCellR#17]
Hi, Rezakj,
Thanks for this powerful l tool.
I ran an issue to run the pseudotime.tree. The error is 
```
Error in `[.data.frame`(x, r, vars, drop = drop) : 
  undefined columns selected
```
MyGenes are correct
```
> MyGenes[1:5]
[1] "Cd209a" "Cd209d" "Il4i1"  "H2.Oa"  "Ccr7" 
```
But when I run the colnames ()
```
> colnames(my.obj)
NULL
```
Whether it means there are no columns, therefore, I can not run the function? But I have got the marker.genes and MyGenes. 

Thanks for your help,
Yale

**Comment by rezakj** [comment]
Hi Yale, 

Thank you for using iCellR, 

And yes my bad, I didn't mention that you need to also run this:

`my.obj <- clust.avg.exp(my.obj) `

Then run it and it should work. 

```
pseudotime.tree(my.obj,
   marker.genes = MyGenes,
   type = "unrooted",
   clust.method = "complete")

```
Reza

**Comment by Yale73** [comment]
Hi Reza,

Thanks so much. It works great. I forgot I merged the Seurat and the iCellR, and skipped some steps.

Thanks again,
Yale
