### ISSUE TITLE
Ploting colonotypes

### ISSUE THREAD

**Issue by crushseven-7** [rezakj/iCellR#20]
Hi there,
I am tring to use these package to analysis my scTCR data. When I try to plot colonotypes, I am quite confused about the `clono` paremeters in `clono.plot` function.  This parameter seems only recepted number rather than raw_clonotype_id in vdj data. I am curious about how can I pre-define this clonotype name.
Best,
Yan

**Comment by rezakj** [comment]
Hi Yan, 

Yes yes, thanks for reminding, I will need to fix a few things for that function.
Will update you today and update the tutorial and let you know.  

Reza

**Comment by crushseven-7** [comment]
Thank you for your quick response. I am really looking forword to it :)

**Comment by rezakj** [comment]
First update iCellR to version 1.5.8. It's not in CRAN yet so update from GitHub. 

Then add your VDJ data to iCellR object
`my.obj <- add.vdj(my.obj, vdj.data = my.vdj.data)`

The rest is explained in detail in the updated section for plotting "How to plot clonotypes".

**Comment by crushseven-7** [comment]
awsome! I tried my data just now, it could not only select the colontype id, even any column in the contig file could be selected to plot. Appreciate for your excellent work.
