### ISSUE TITLE
TPM instead of count data & no conditions

### ISSUE THREAD

**Issue by nicholascwho** [rezakj/iCellR#22]
Hi @rezakj 

Thank you for this great resource! I was just wondering, if I only have TPM data instead of count data, would that be okay for make.obj()?

Also, if I have no conditions like in example 1, how would I use data.aggregation()? And would it affect the later function calls?

Thanks!

**Comment by rezakj** [comment]
Yes, you can use iCellR. If you already have normalized the data skip the normalization step. 

If you have only one sample skip the aggregation step.

**Comment by nicholascwho** [comment]
Okay, thank you so much!
