### ISSUE TITLE
Labelling cells with cluster

### ISSUE THREAD

**Issue by nicholascwho** [rezakj/iCellR#23]
Hi @rezakj 

Thanks again for this resource. I was wondering if there is any function or iCellR object parameter that can label each cell with the specific cluster?

Thank you!

**Comment by rezakj** [comment]
Let's say cluster 7 is "B cells" and instead of 7 you want it to show B Cells:

`my.obj <- change.clust(my.obj, change.clust = 7, to.clust = "7-B_Cells")`

**Comment by nicholascwho** [comment]
Hi @rezakj 

Thank you. What about finding all the cells within each cluster? What I mean is: once i get each cluster, how can I know which of the cells from the scRNAseq data belong to which cluster? For example, if I have a cluster of B cells, I would like to know the specific cell IDs that belong to the B cell cluster.

Thanks!

**Comment by rezakj** [comment]
```
cell.cluster <- (my.obj@best.clust)
head(cell.cluster)
```

**Comment by nicholascwho** [comment]
That works! Thank you!
