### ISSUE TITLE
Seeking help to create different types of plots

### ISSUE THREAD

**Issue by Rashidul1990** [rezakj/iCellR#33]
I would be highly grateful if you can answer the following questions- 
1. How to make a vector for more than one gene and display it in DotPlot?
2. How to do co-expression analysis of two markers and create bicolored co-marker gradients in FeaturePlot?
3. I want to present the average gene expression of a specific in Violin plots?
4. How to do RidgePlot in iCellR?

**Comment by rezakj** [comment]
Hi, 



Reza

**Comment by rezakj** [comment]
Hi, 

iCellR dose not make 2 color plots but you can use the command below to export the expression of the genes you like and use ggplot2 to plot with 2 colors.

`gene.plot(my.obj, gene = "MS4A1", write.data = T, scaleValue = F, data.type = "main")`

For co-expression use gene-gene correlation plots, example below:

`gg.cor(my.obj, 
	interactive = F, 
	gene1 = "GNLY",
	gene2 = "NKG7", 
	conds = NULL,
	clusts = NULL,
	data.type = "imputed")`

**Comment by Rashidul1990** [comment]
Thanks very much for your kind response. 

1st command work perfectly fine but the second command for gene-gene correlation plots give erros as-

>gg.cor(my.obj, interactive = F, gene1 = "CD3D", gene2 = "PTPRC", conds = NULL, clusts = NULL, data.type = "imputed")

Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 14555, 0

Would you please further suggest solving this error?
 
Many thanks and best regards,
Rashidul

**Comment by rezakj** [comment]
Did you impute the data before running it and also ran clustering?
