### ISSUE TITLE
Possible to cluster based on ADT data alone?

### ISSUE THREAD

**Issue by cpcook1** [rezakj/iCellR#4]
Hi I was wondering if it is possible to cluster on the ADT data alone, and if so, how to go about it? When I try using Seurat and PCA I get a warning message "The object only has information for 25 reductions" since we have only run 25 Abs, and subsequently we only get 1-2 PC's.

If I try using creating a distance matrix as per the seurat vignette the object is too large and the computer will not accept it. Is it possible in iCellR?

**Comment by rezakj** [comment]
Yes, it's possible to cluster based on ADTs. Here is how it works:

1- get you ADT names from the main data slot:

```r
grep("^ADT_", rownames(my.obj@main.data),value=T)
# [1] "ADT_CD3"    "ADT_CD4"    "ADT_CD8"    "ADT_CD45RA" "ADT_CD56"
# [6] "ADT_CD16"   "ADT_CD11c"  "ADT_CD14"   "ADT_CD19"   "ADT_CD34"

MyADTS <- grep("^ADT_", rownames(my.obj@main.data),value=T)
```

2- Run PCA based on ADTs and all is good. Because, tSNE and UMAP will be running based on PCA the rest of your analysis will be based on ADTs. 

`my.obj <- run.pca(my.obj, 
                                 method = "gene.model", 
                                 gene.list = MyADTS, 
                                 data.type = "main")
`
