### ISSUE TITLE
Coloring not working for TSNE and UMAP plots for option color by = "Cluster"

### ISSUE THREAD

**Issue by IkjotSidhu** [rezakj/iCellR#6]
Coloring by the cluster is not working for umap and tsne plots-
```{r}
> cluster.plot(my.obj,plot.type = "umap",interactive = F)
```
Error: Aesthetics must be either length 1 or the same as the data (36689): colour

```{r}
> cluster.plot(my.obj,plot.type = "umap",interactive = F,col.by="clusters")
```
Error: Aesthetics must be either length 1 or the same as the data (36689): colour

**Comment by rezakj** [comment]
Run clustering and UMAP again and see if you get an error. Also update iCellR from CRAN.

```
library(devtools)
install_github("rezakj/iCellR")

```

Then:

```
# quick example 
library(Rphenograph)
my.obj <- run.phenograph(my.obj, k = 100, dims = 1:10)

my.obj <- run.umap(my.obj, dims = 1:10, method = "umap-learn") 
```

Let me know if this didn't help.

**Comment by IkjotSidhu** [comment]
I am getting an error while trying to install another required package called - digest.


* installing *source* package ‘digest’ ...
** package ‘digest’ successfully unpacked and MD5 sums checked
** libs
g++ -std=gnu++11 -I"/gpfs/share/apps/R/3.5.1/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2 -c SpookyV2.cpp -o SpookyV2.o
gcc -I"/gpfs/share/apps/R/3.5.1/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c aes.c -o aes.o
gcc -I"/gpfs/share/apps/R/3.5.1/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c crc32.c -o crc32.o
gcc -I"/gpfs/share/apps/R/3.5.1/lib64/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c digest.c -o digest.o
digest.c: In function ‘vdigest’:
digest.c:475:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (R_xlen_t i = 0; i < n; i++){
         ^
digest.c:475:9: note: use option -std=c99 or -std=gnu99 to compile your code
digest.c:480:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (R_xlen_t i = 0; i < n; i++){
         ^
make: *** [digest.o] Error 1
ERROR: compilation failed for package ‘digest’
* removing ‘/gpfs/data/feskelab/R/x86_64-pc-linux-gnu-library/3.5/digest’
Error: Failed to install 'Rphenograph' from GitHub:
  (converted from warning) installation of package ‘digest’ had non-zero exit status

**Comment by IkjotSidhu** [comment]
![image](https://user-images.githubusercontent.com/35705259/67721431-df721e80-f9ac-11e9-8265-c939dbca3837.png)

I think that I found the cause of the error. It seems that even after performing batch correction using MNN and Running dimensionality reduction, the object does not contain cluster information.

**Comment by rezakj** [comment]
Yes, you would need to run clustering after batch correction.
